base_url = "https://eruption-project.org/"

title = "Eruption"
theme = "zolastrap"
# generate_feed = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    {name = "authors", rss = true},
]

vapor_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# highlight_theme = "monokai"

[extra]
# Put all your custom variables here
theme = "vapor"
bg = "dark"
banner = "/img/banner.jpeg"
# themes = []
# schemes = []

# email = "x3n0m0rph59@gmail.com"

icons = [
    {title = 'GitHub', icon = 'github', url = 'https://github.com/eruption-project/eruption'},
    {title = 'YouTube', icon = 'youtube', url = 'https://www.youtube.com/@eruption714'}
]

links = [
    {title = 'Devices', url = 'devices'},
    {title = 'Installation', url = '#installation'},
    # {title = 'Downloads', url = 'downloads'},
    {title = 'Gallery', url = 'gallery'},
    {title = 'Blog', url = 'articles'},
    {title = 'About', url = 'about'},
    {title = 'Docs', url = 'https://github.com/eruption-project/eruption/tree/master/docs#table-of-contents'},
    {title = 'Issues', url = 'https://github.com/eruption-project/eruption/issues'},
]

# [extra.show]
# tags = true
